"""Decide where the sound effects go, from the storyboard alone.

The six cues in assets/sfx were generated by gen_sfx.py and then never used by
anything. They are worth using: sound is the one kind of emphasis that costs
nothing to render, works in the MP4 and the draft alike, and does not touch a
single pixel - so none of the measurements the picture is built on are at risk.

Where a cue goes is derived, not authored. The storyboard already says which
shot has a label, which has money in it, which has a board, and where the
shots change; that is enough, and it means a sound design falls out of a script
without anyone placing anything by hand.

The restraint matters more than the cues. Sound is much easier to overdo than
picture: a whoosh on every shot plus a pop on every label plus a coin on every
figure turns a calm explainer into a slot machine. Hence a hard cap per shot,
a quiet default gain, and cues that are off unless the shot has a reason.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import render as render_mod
import styles as styles_mod

ROOT = Path(__file__).resolve().parent.parent
SFX_DIR = ROOT / "assets" / "sfx"

# A transition cue lands slightly before the cut, the way an editor would place
# it: the sound leads the picture, so the change feels caused rather than
# noticed. Everything else lands on its own moment.
TRANSITION_LEAD = 0.08


def library():
    """{name: path} for every effect on disk."""
    if not SFX_DIR.is_dir():
        return {}
    return {f.stem: f for f in sorted(SFX_DIR.glob("*.wav"))}


def _has(scene, predicate):
    return any(predicate(el) for el in scene.get("elements") or [])


def carried(storyboard):
    """The cue list a storyboard recorded, resolved back to paths.

    Planned once, when the storyboard is built and the cast is in hand, then
    carried like `look` and `panel_color`. The mix and the draft then cannot
    disagree - which they did: the draft plans without a cast, could not tell a
    writable board from any other prop, and quietly produced one cue fewer than
    the MP4.
    """
    have = library()
    out = []
    for entry in storyboard.get("sound_cues") or []:
        try:
            when, name = float(entry[0]), str(entry[1])
        except (TypeError, ValueError, IndexError):
            continue
        if name in have:
            out.append((when, name, have[name]))
    return out


def plan(storyboard, durations, cast=None, look=None):
    """Return [(seconds, name, path)] for the whole video, in time order.

    `cast` is optional and only sharpens the board cue - without it a writable
    prop cannot be told from any other prop, and that cue is simply skipped
    rather than fired on everything.
    """
    look = look or styles_mod.look(carried=(storyboard.get("video") or {}).get("look"))
    config = look.get("sound") or {}
    have = library()
    if not config.get("enabled", True) or not have:
        return []

    gain_cap = int(config.get("max_per_shot", 2))
    segments, _ = render_mod.build_timeline(storyboard, durations)
    cues = []

    for segment in segments:
        if segment.kind == "ending":
            name = config.get("ending")
            if name in have:
                cues.append((segment.start, name))
            continue
        if segment.kind != "scene":
            continue

        shot = []
        # The cut itself. Not on the first shot: there is nothing to cut from,
        # and a whoosh over the title card reads as a mistake.
        if segment.index > 0 and config.get("transition") in have:
            shot.append((max(0.0, segment.start - TRANSITION_LEAD),
                         config["transition"]))

        scene = segment.data
        money = config.get("money")
        if money in have and (
                _has(scene, lambda el: el.get("tone") == "money")
                or _has(scene, lambda el: "coin" in (el.get("asset") or "")
                        or "money" in (el.get("asset") or ""))):
            cues_at = segment.start + 0.18
            shot.append((cues_at, money))
        elif config.get("label") in have and _has(
                scene, lambda el: el.get("type") in ("label", "bubble")):
            # A label and a coin at the same instant is a pile-up; the coin
            # already says "this is about money", which is the more specific
            # of the two.
            appear = min((float(el.get("appear", 0.0)) for el in scene["elements"]
                          if el.get("type") in ("label", "bubble")), default=0.0)
            shot.append((segment.start + max(appear, 0.15), config["label"]))

        board = config.get("board")
        if board in have and cast is not None and _has(
                scene, lambda el: el.get("asset") and cast.writable(el["asset"])):
            shot.append((segment.start + 0.30, board))

        cues.extend(sorted(shot)[:gain_cap])

    return [(when, name, have[name]) for when, name in sorted(cues)]


def describe(cues):
    """One line per distinct cue, for the build log."""
    counts = {}
    for _, name, _ in cues:
        counts[name] = counts.get(name, 0) + 1
    return ", ".join(f"{name} x{n}" for name, n in sorted(counts.items()))
